/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteModal: typeof import('./src/components/deleteModal.vue')['default']
    EditModal: typeof import('./src/components/editModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PersonsTableView: typeof import('./src/components/personsTableView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpsertModal: typeof import('./src/components/upsertModal.vue')['default']
  }
}
